apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  http:
  - match:
    #- headers:
    #    end-user:
    #      exact: jason
    - headers:
        x-request-id:
           regex: ".*fail=reviews.*"
    fault:
      delay:
        percentage:
          value: 100.0
        fixedDelay: 60s
    route:
    - destination:
        host: reviews
        subset: v1
  - route:
    - destination:
        host: reviews
        subset: v1
